//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DapperSpGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DapperSpGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Dapper;
        ///using System.Data;
        ///
        ///namespace |^NAMESPACE^|
        ///{
        ///    /// &lt;summary&gt;
        ///    /// This class is automatically generated, to extend this class, please use a partial class.
        ///    /// &lt;/summary&gt;
        ///    public static partial class DapperCommandExtensions
        ///    {
        ///        public static async Task&lt;IEnumerable&lt;T&gt;&gt; QueryAsync&lt;T&gt;(this IDbConnection dbConnection, IDatabaseCommand command, IDbTransaction? transaction = null, int? commandTimeout = null)
        ///        {
        ///            var parameters = command.GetParamete [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DapperCommandExtensions {
            get {
                return ResourceManager.GetString("DapperCommandExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using Dapper;
        ///using System.Data;
        ///
        ///namespace |^NAMESPACE^|
        ///{
        ///    /// &lt;summary&gt;
        ///    /// This class is automatically generated.
        ///    /// &lt;/summary&gt;
        ///    public interface IDatabaseCommand
        ///    {
        ///        DynamicParameters GetParameters();
        ///        CommandType GetCommandType();
        ///        string GetSqlStatement();
        ///        bool HasOutParameters();
        ///        void SetOutParameters(DynamicParameters parameters);
        ///    }
        ///}.
        /// </summary>
        internal static string IDatabaseCommand {
            get {
                return ResourceManager.GetString("IDatabaseCommand", resourceCulture);
            }
        }
    }
}
